import type { Team } from './types'

export const teams2026: Team[] = [
  { id: 'canada', name: 'Canada', group: 'A', order: 1 },
  { id: 'mexico', name: 'Mexico', group: 'A', order: 2 },
  { id: 'usa', name: 'USA', group: 'A', order: 3 },
  { id: 'australia', name: 'Australia', group: 'B', order: 4 },
  { id: 'iraq', name: 'Iraq', group: 'B', order: 5 },
  { id: 'ir-iran', name: 'IR Iran', group: 'B', order: 6 },
  { id: 'japan', name: 'Japan', group: 'B', order: 7 },
  { id: 'jordan', name: 'Jordan', group: 'B', order: 8 },
  { id: 'korea-republic', name: 'Korea Republic', group: 'C', order: 9 },
  { id: 'qatar', name: 'Qatar', group: 'C', order: 10 },
  { id: 'saudi-arabia', name: 'Saudi Arabia', group: 'C', order: 11 },
  { id: 'uzbekistan', name: 'Uzbekistan', group: 'C', order: 12 },
  { id: 'algeria', name: 'Algeria', group: 'D', order: 13 },
  { id: 'cabo-verde', name: 'Cabo Verde', group: 'D', order: 14 },
  { id: 'congo-dr', name: 'Congo DR', group: 'D', order: 15 },
  { id: 'cote-divoire', name: "Cote d'Ivoire", group: 'D', order: 16 },
  { id: 'egypt', name: 'Egypt', group: 'E', order: 17 },
  { id: 'ghana', name: 'Ghana', group: 'E', order: 18 },
  { id: 'morocco', name: 'Morocco', group: 'E', order: 19 },
  { id: 'senegal', name: 'Senegal', group: 'E', order: 20 },
  { id: 'south-africa', name: 'South Africa', group: 'F', order: 21 },
  { id: 'tunisia', name: 'Tunisia', group: 'F', order: 22 },
  { id: 'curacao', name: 'Curacao', group: 'F', order: 23 },
  { id: 'haiti', name: 'Haiti', group: 'F', order: 24 },
  { id: 'panama', name: 'Panama', group: 'G', order: 25 },
  { id: 'argentina', name: 'Argentina', group: 'G', order: 26 },
  { id: 'brazil', name: 'Brazil', group: 'G', order: 27 },
  { id: 'colombia', name: 'Colombia', group: 'G', order: 28 },
  { id: 'ecuador', name: 'Ecuador', group: 'H', order: 29 },
  { id: 'paraguay', name: 'Paraguay', group: 'H', order: 30 },
  { id: 'uruguay', name: 'Uruguay', group: 'H', order: 31 },
  { id: 'new-zealand', name: 'New Zealand', group: 'H', order: 32 },
  { id: 'austria', name: 'Austria', group: 'I', order: 33 },
  { id: 'belgium', name: 'Belgium', group: 'I', order: 34 },
  { id: 'bosnia-herzegovina', name: 'Bosnia and Herzegovina', group: 'I', order: 35 },
  { id: 'croatia', name: 'Croatia', group: 'I', order: 36 },
  { id: 'czechia', name: 'Czechia', group: 'J', order: 37 },
  { id: 'england', name: 'England', group: 'J', order: 38 },
  { id: 'france', name: 'France', group: 'J', order: 39 },
  { id: 'germany', name: 'Germany', group: 'J', order: 40 },
  { id: 'netherlands', name: 'Netherlands', group: 'K', order: 41 },
  { id: 'norway', name: 'Norway', group: 'K', order: 42 },
  { id: 'portugal', name: 'Portugal', group: 'K', order: 43 },
  { id: 'scotland', name: 'Scotland', group: 'K', order: 44 },
  { id: 'spain', name: 'Spain', group: 'L', order: 45 },
  { id: 'sweden', name: 'Sweden', group: 'L', order: 46 },
  { id: 'switzerland', name: 'Switzerland', group: 'L', order: 47 },
  { id: 'turkiye', name: 'Turkiye', group: 'L', order: 48 },
]
