import type { Team } from './types'

export const teams2026: Team[] = [
  { id: 'canada', name: 'Canada', flag: '🇨🇦', group: 'A', order: 1 },
  { id: 'mexico', name: 'Mexico', flag: '🇲🇽', group: 'A', order: 2 },
  { id: 'usa', name: 'USA', flag: '🇺🇸', group: 'A', order: 3 },
  { id: 'australia', name: 'Australia', flag: '🇦🇺', group: 'B', order: 4 },
  { id: 'iraq', name: 'Iraq', flag: '🇮🇶', group: 'B', order: 5 },
  { id: 'ir-iran', name: 'IR Iran', flag: '🇮🇷', group: 'B', order: 6 },
  { id: 'japan', name: 'Japan', flag: '🇯🇵', group: 'B', order: 7 },
  { id: 'jordan', name: 'Jordan', flag: '🇯🇴', group: 'B', order: 8 },
  { id: 'korea-republic', name: 'Korea Republic', flag: '🇰🇷', group: 'C', order: 9 },
  { id: 'qatar', name: 'Qatar', flag: '🇶🇦', group: 'C', order: 10 },
  { id: 'saudi-arabia', name: 'Saudi Arabia', flag: '🇸🇦', group: 'C', order: 11 },
  { id: 'uzbekistan', name: 'Uzbekistan', flag: '🇺🇿', group: 'C', order: 12 },
  { id: 'algeria', name: 'Algeria', flag: '🇩🇿', group: 'D', order: 13 },
  { id: 'cabo-verde', name: 'Cabo Verde', flag: '🇨🇻', group: 'D', order: 14 },
  { id: 'congo-dr', name: 'Congo DR', flag: '🇨🇩', group: 'D', order: 15 },
  { id: 'cote-divoire', name: "Cote d'Ivoire", flag: '🇨🇮', group: 'D', order: 16 },
  { id: 'egypt', name: 'Egypt', flag: '🇪🇬', group: 'E', order: 17 },
  { id: 'ghana', name: 'Ghana', flag: '🇬🇭', group: 'E', order: 18 },
  { id: 'morocco', name: 'Morocco', flag: '🇲🇦', group: 'E', order: 19 },
  { id: 'senegal', name: 'Senegal', flag: '🇸🇳', group: 'E', order: 20 },
  { id: 'south-africa', name: 'South Africa', flag: '🇿🇦', group: 'F', order: 21 },
  { id: 'tunisia', name: 'Tunisia', flag: '🇹🇳', group: 'F', order: 22 },
  { id: 'curacao', name: 'Curacao', flag: '🇨🇼', group: 'F', order: 23 },
  { id: 'haiti', name: 'Haiti', flag: '🇭🇹', group: 'F', order: 24 },
  { id: 'panama', name: 'Panama', flag: '🇵🇦', group: 'G', order: 25 },
  { id: 'argentina', name: 'Argentina', flag: '🇦🇷', group: 'G', order: 26 },
  { id: 'brazil', name: 'Brazil', flag: '🇧🇷', group: 'G', order: 27 },
  { id: 'colombia', name: 'Colombia', flag: '🇨🇴', group: 'G', order: 28 },
  { id: 'ecuador', name: 'Ecuador', flag: '🇪🇨', group: 'H', order: 29 },
  { id: 'paraguay', name: 'Paraguay', flag: '🇵🇾', group: 'H', order: 30 },
  { id: 'uruguay', name: 'Uruguay', flag: '🇺🇾', group: 'H', order: 31 },
  { id: 'new-zealand', name: 'New Zealand', flag: '🇳🇿', group: 'H', order: 32 },
  { id: 'austria', name: 'Austria', flag: '🇦🇹', group: 'I', order: 33 },
  { id: 'belgium', name: 'Belgium', flag: '🇧🇪', group: 'I', order: 34 },
  { id: 'bosnia-herzegovina', name: 'Bosnia and Herzegovina', flag: '🇧🇦', group: 'I', order: 35 },
  { id: 'croatia', name: 'Croatia', flag: '🇭🇷', group: 'I', order: 36 },
  { id: 'czechia', name: 'Czechia', flag: '🇨🇿', group: 'J', order: 37 },
  { id: 'england', name: 'England', flag: '🏴', group: 'J', order: 38 },
  { id: 'france', name: 'France', flag: '🇫🇷', group: 'J', order: 39 },
  { id: 'germany', name: 'Germany', flag: '🇩🇪', group: 'J', order: 40 },
  { id: 'netherlands', name: 'Netherlands', flag: '🇳🇱', group: 'K', order: 41 },
  { id: 'norway', name: 'Norway', flag: '🇳🇴', group: 'K', order: 42 },
  { id: 'portugal', name: 'Portugal', flag: '🇵🇹', group: 'K', order: 43 },
  { id: 'scotland', name: 'Scotland', flag: '🏴', group: 'K', order: 44 },
  { id: 'spain', name: 'Spain', flag: '🇪🇸', group: 'L', order: 45 },
  { id: 'sweden', name: 'Sweden', flag: '🇸🇪', group: 'L', order: 46 },
  { id: 'switzerland', name: 'Switzerland', flag: '🇨🇭', group: 'L', order: 47 },
  { id: 'turkiye', name: 'Turkiye', flag: '🇹🇷', group: 'L', order: 48 },
]
